### ISSUE TITLE
TLS handshake with official cert fails if custom certs are specified

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/go-tpm#1]
Using a self-signed cert is fine. However, using an officially signed one (like you get when using AWS), ros-installer fails with
```
x509: certificate signed by unknown authority 
```

It looks as if go-tpm uses https://pkg.go.dev/crypto/tls#Config wrongly, as it sets the cert as `RootCAs`, effectively overriding the use of root CAs installed on the host (in /var/lib/ca-certificates)

**Comment by mudler** [comment]
overriding certs and appending are different things. if a CA is specified it is expected to respect that. I don't see why passing custom cert in the first place if system CA is used at the end to verify?

**Comment by kkaempf** [comment]
We need to verify two things when establishing the connection to the server
- the server has a valid cert (this needs RootCAs)
- we're talking to the right server (this needs something different)

**Comment by mudler** [comment]
> We need to verify two things when establishing the connection to the server
> 
>     * the server has a valid cert (this needs RootCAs)

This is what the TLS mechanism is for

> 
>     * we're talking to the right server (this needs something different)

This is what TPM provides here, otherwise we should have been using something like gpg, or..?

**Comment by mudler** [comment]
https://github.com/rancher-sandbox/go-tpm/pull/2 adds an option to enable to append to the systemCA pool. It adds a bunch of tests that needs to be run manually against a ros endpoint
